name: plenoctree
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.8.8
  - numpy>=1.16.4,<1.19.0
  - tqdm
  - pip
  - pip:
      - dotmap
      - imageio
      - imageio-ffmpeg
      - ipdb
      - pretrainedmodels
      - lpips
      - jax==0.2.9
      - jaxlib>=0.1.57
      - flax>=0.3.1
      - opencv-python>=4.4.0
      - Pillow>=7.2.0
      - pyyaml>=5.3.1
      - torch>=1.7.0,<=1.7.1
      - tensorboard>=2.4.0
      - tensorflow>=2.3.1
      - imageio
      - imageio-ffmpeg
      - pymcubes
      - scipy>=1.6.0
      - pyquaternion
      - trimesh
      - open3d
